cargo-features = ["profile-overrides"]
[package]
name = "iris"
version = "0.1.0"
authors = ["Tatsuyuki Ishi <ishitatsuyuki@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = { path = "../amethyst", default-features = false }
failure = "0.1.5"
lazy_static = "1.3.0"
glsl-layout = "0.3.0"
superslice = "1.0.0"
ron = "0.5.1"
serde = { version = "1.0.100", features = ["derive"] }
rodio = "0.9.0"

[features]
default = ["amethyst/animation", "amethyst/renderer", "amethyst/vulkan"]

[profile.dev]
opt-level = 0

[profile.dev.overrides."*"]
opt-level = 2
debug = false 
